import fs from 'fs';
import path from 'path';

const faqData = {
  "gst-error-report.astro": [
    { q: "What is a GST error report in 2026?", a: "A GST error report highlights the discrepancies and errors that occurred during the JSON payload upload to the official GST portal. In 2026, parsing this report offline helps businesses fix syntax and schema errors securely." },
    { q: "How can I fix GST portal JSON errors?", a: "To fix GST JSON errors, download the error report JSON from the portal, upload it to our free offline tool, and view the exact line and invoice number that caused the issue. Then, correct your source ERP data and regenerate the JSON." },
    { q: "Is this GST error report tool safe to use?", a: "Yes. Our GST error report tool runs 100% locally in your browser. None of your sensitive invoice data or error logs are uploaded to any server, ensuring complete data privacy." },
    { q: "Why do I get 'Invalid GSTIN' errors in GSTR-1?", a: "This happens when the buyer's GSTIN is cancelled, suspended, or incorrectly formatted. Our error report tool will pinpoint exactly which invoice contains the invalid GSTIN." },
    { q: "Can I convert the GST error report to Excel?", a: "While this specific tool reads and formats the error JSON, you can use our GSTR-1 JSON to Excel tool to convert your entire return data, including errors, into a readable Excel format." },
    { q: "Does this tool support GST 2.0 error schemas?", a: "Yes, our tool is updated for 2026 and fully supports the latest GST 2.0 error JSON schemas provided by the GSTN." },
    { q: "Why is the GST portal showing 'Processed with Error'?", a: "This status means your return file was accepted, but specific invoices or records failed validation. You must download the error report and use our tool to decode which records failed." },
    { q: "Can I use this tool on my mobile phone?", a: "Yes, our GST offline tools are fully responsive and work seamlessly on mobile browsers without requiring a dedicated app download." },
    { q: "Do I need to login to view GST errors here?", a: "No login is required. Taxzentic's tools are completely free and accessible instantly without any sign-up or subscription." }
  ],
  "gstr1-json-to-excel.astro": [
    { q: "How do I convert GSTR-1 JSON to Excel offline?", a: "Simply drag and drop your GSTR-1 JSON file downloaded from the GST portal or generated by your ERP into our tool. It will instantly convert it to a structured Excel (.xlsx) file completely offline." },
    { q: "Is it safe to convert GSTR-1 JSON online?", a: "With our tool, yes. The conversion from GSTR-1 JSON to Excel happens entirely within your web browser. Your financial data is never sent to our servers." },
    { q: "Why should I convert GSTR-1 JSON to Excel?", a: "Converting GSTR-1 JSON to Excel allows you to easily read, filter, and reconcile your outward supplies and B2B invoices before filing, ensuring maximum accuracy for 2026 audits." },
    { q: "Does the tool separate B2B and B2C invoices?", a: "Yes, the generated Excel file contains separate sheets for B2B, B2CL, B2CS, CDNR, and HSN summaries, matching the exact structure of the GST return." },
    { q: "Can this tool handle large GSTR-1 JSON files?", a: "Yes, because it runs locally using your device's memory, it can process large JSON files with thousands of invoices much faster than cloud-based converters." },
    { q: "Is this tool updated for the latest 2026 GST schemas?", a: "Absolutely. The converter is fully compatible with the GST 2.0 schemas introduced for FY 2025-26." },
    { q: "Do I need Microsoft Excel installed to use this tool?", a: "No, you don't need Excel to run the tool, but you will need Excel, Google Sheets, or a compatible spreadsheet viewer to open the downloaded .xlsx file." },
    { q: "Can I edit the GSTR-1 data after converting to Excel?", a: "Yes, you can edit the downloaded Excel file. However, to file it on the portal, you will need to convert it back to JSON using the official GST offline utility." },
    { q: "Are there any file size limits?", a: "There are no strict file size limits imposed by our servers since the processing happens in your browser. However, extremely large files (50MB+) may slow down your browser." }
  ],
  "gstr1-json-validator.astro": [
    { q: "What is a GSTR-1 JSON Validator?", a: "A GSTR-1 JSON Validator is a tool that checks your GST return file for schema errors, missing fields, and structural issues before you upload it to the official GST portal." },
    { q: "How do I check if my GSTR-1 JSON is valid for 2026?", a: "Upload your JSON file to our offline validator. It instantly checks the file against the latest 2026 GSTN schema rules and highlights any errors." },
    { q: "Why does the GST portal reject my JSON file?", a: "The portal rejects files if they contain invalid characters, incorrect GSTIN formats, missing mandatory fields, or mismatched tax rates. Our tool helps you catch these before uploading." },
    { q: "Is my GSTR-1 data uploaded to your server?", a: "No. The validation happens 100% offline within your browser. Your invoice details remain completely private and secure." },
    { q: "Does it validate HSN codes and tax rates?", a: "It validates the structure and format of the HSN codes and tax rates against the expected schema, but it does not cross-verify the actual tax rate of a specific HSN code against the live government database." },
    { q: "Can I use this for GSTR-3B JSON files?", a: "Currently, this specific tool is optimized for GSTR-1 JSON schemas. We recommend using our other utilities for GSTR-3B." },
    { q: "What are common GSTR-1 JSON errors?", a: "Common errors include duplicate invoice numbers, incorrect date formats (DD-MM-YYYY required), and invalid state codes for inter-state supplies." },
    { q: "Is this tool free for CAs and businesses?", a: "Yes, Taxzentic provides this validator entirely free of charge with no limits on the number of files you can check." },
    { q: "How fast is the offline JSON validation?", a: "Because it relies on your local device CPU rather than a network request, validation is virtually instantaneous, even for large files." }
  ],
  "gst-state-codes.astro": [
    { q: "What is a GST state code?", a: "A GST state code is a unique 2-digit number assigned to each state and union territory in India. It forms the first two digits of any 15-digit GSTIN." },
    { q: "Why is the GST state code important for billing?", a: "The state code helps determine the Place of Supply. If the supplier's state code and the buyer's state code match, CGST+SGST applies. If they differ, IGST applies." },
    { q: "What is the GST state code for Maharashtra in 2026?", a: "The GST state code for Maharashtra remains '27'. The state codes have not changed in the 2026 GST 2.0 update." },
    { q: "How can I find the state name from a GSTIN?", a: "Simply look at the first two digits of the GSTIN and match it against our GST state code list. For example, '07' is Delhi and '29' is Karnataka." },
    { q: "Are state codes different from union territory codes?", a: "No, under GST, both states and union territories are assigned 2-digit codes in the exact same format (from 01 to 38)." },
    { q: "What does state code '97' mean?", a: "State code '97' is reserved for 'Other Territory' under the GST framework, typically used for specific offshore or specialized economic zones." },
    { q: "Can a business have multiple GSTINs in the same state?", a: "Yes. If a business has multiple verticals or branches in the same state, they can obtain multiple GSTINs. The state code (first two digits) will remain the same, but the entity code (13th digit) will change." },
    { q: "Where can I download the full list of GST state codes?", a: "You can view, search, and refer to the complete, updated 2026 list of GST state codes directly on our page." }
  ],
  "gstr-2b-reconciliation-tool.astro": [
    { q: "What is GSTR-2B reconciliation in 2026?", a: "GSTR-2B reconciliation involves matching your purchase register (books) against the auto-drafted GSTR-2B statement from the GST portal to claim accurate Input Tax Credit (ITC)." },
    { q: "Why do I need an offline GSTR-2B reconciliation tool?", a: "An offline tool ensures your financial data stays private while allowing you to instantly identify missing invoices, mismatches in tax amounts, and vendors who haven't filed their returns." },
    { q: "How does this tool match invoices?", a: "It compares the invoice number, GSTIN, date, and tax amounts between your purchase register Excel and the GSTR-2B JSON/Excel using advanced fuzzy matching and exact matching algorithms." },
    { q: "What happens if a vendor invoice is missing from GSTR-2B?", a: "If an invoice is missing from GSTR-2B, you cannot claim ITC for it in that month under the strict 2026 ITC rules. You must follow up with the vendor to file their GSTR-1." },
    { q: "Does this tool support the latest GST 2.0 formats?", a: "Yes, our GSTR-2B reconciliation engine is fully updated for the 2026 financial year formats and schema requirements." },
    { q: "Can it handle large datasets?", a: "Yes. Since it runs in your browser using local resources, it can process thousands of rows of purchase data without server timeouts." },
    { q: "Are there any limits on the number of reconciliations?", a: "No. You can run as many GSTR-2B reconciliations as you want, completely free of charge." },
    { q: "What should I do with the mismatched records?", a: "Our tool generates a clear report of mismatched and missing invoices. You can export this report and use it to follow up with your suppliers for corrections." }
  ],
  "merge-excel-files.astro": [
    { q: "How do I merge multiple Excel files online safely?", a: "You can drag and drop multiple Excel files into our tool. It merges them into a single workbook offline in your browser, guaranteeing your data privacy." },
    { q: "Why merge Excel files for GST filing?", a: "Businesses often download multiple GSTR-2B, error reports, or branch-wise sales data. Merging them into one master Excel file makes reconciliation and filtering much easier." },
    { q: "Does the tool preserve Excel sheets during merging?", a: "Yes. Our tool can either append data from identically named sheets together or combine different files into separate sheets within the master workbook." },
    { q: "Is there a limit to how many files I can merge?", a: "There is no hard limit on the number of files, but merging dozens of massive files may consume significant browser memory." },
    { q: "Do I need to install any software to merge files?", a: "No installation is required. The merging process uses WebAssembly and JavaScript directly in your web browser." },
    { q: "Does it support .csv and .xlsx formats?", a: "Yes, our tool supports both modern .xlsx files and standard .csv files, converting them seamlessly into one output format." },
    { q: "Will the formatting of my Excel files be lost?", a: "Basic data and structure are perfectly preserved. However, complex macros, charts, or advanced conditional formatting may not carry over during the merge." },
    { q: "Are my merged files stored on your servers?", a: "Absolutely not. The entire file reading, merging, and downloading process happens on your local device." }
  ],
  "invoice-generator.astro": [
    { q: "Is this GST invoice generator free to use?", a: "Yes, our GST invoice generator is 100% free. You can generate unlimited invoices without any watermarks or hidden charges." },
    { q: "Can I add my own company logo to the invoice?", a: "Yes, you can upload your company logo directly in the tool, and it will be beautifully formatted on the final PDF invoice." },
    { q: "Does the invoice format comply with 2026 GST rules?", a: "Absolutely. Our invoice template includes all mandatory fields required by the CGST Act, including HSN/SAC codes, GSTINs, Place of Supply, and tax breakdown." },
    { q: "Are my invoice details saved online?", a: "No. For your privacy and security, all invoice generation happens locally in your browser. We do not store your client or pricing data on any database." },
    { q: "How do I add IGST or CGST/SGST?", a: "Simply select the 'Place of Supply' state. If it matches your business state, the tool automatically splits the tax into CGST and SGST. If it differs, it applies IGST." },
    { q: "Can I download the invoice as a PDF?", a: "Yes, once you fill in the details, click 'Download PDF' to instantly save a professional, print-ready PDF invoice to your device." }
  ],
  "gst-registration-checker.astro": [
    { q: "How can I verify a GST registration status offline?", a: "Our offline GST registration checker validates the structural integrity and mathematical checksum of the GSTIN. For live portal status (Active/Cancelled), you must check the official GST portal." },
    { q: "Why is checking GST registration important?", a: "Verifying a supplier's GST registration ensures you are dealing with a legitimate business and prevents you from losing Input Tax Credit (ITC) due to fake invoices." },
    { q: "What does the 15-digit GSTIN consist of?", a: "It consists of a 2-digit state code, 10-digit PAN, 1-digit entity code, a default 'Z', and a 1-digit mathematical checksum." },
    { q: "Can this tool extract the PAN from the GSTIN?", a: "Yes, the tool automatically decodes and displays the 10-character PAN embedded within the GSTIN." },
    { q: "Does it show the state of the registered business?", a: "Yes, it parses the first two digits of the GSTIN to instantly display the state or union territory of the business." }
  ],
  "composition-scheme-calculator.astro": [
    { q: "What is the GST composition scheme limit for 2026?", a: "For most states, the turnover limit for the GST composition scheme is ₹1.5 crore. For North-Eastern and special category states, it is ₹75 lakhs." },
    { q: "Can a composition dealer collect GST from customers?", a: "No. A composition dealer cannot charge GST on their invoices (they issue a 'Bill of Supply') and cannot claim Input Tax Credit." }
  ],
  "eway-bill-limit-checker.astro": [
    { q: "What is the e-way bill limit for inter-state transport?", a: "The threshold limit for generating an e-way bill for inter-state movement of goods is ₹50,000 (invoice value including GST)." },
    { q: "Are there different e-way bill limits for intra-state transport?", a: "Yes, intra-state limits vary by state. Some states have a limit of ₹50,000, while others like Maharashtra have increased it to ₹1,00,000 for certain goods." }
  ],
  "eway-bill-validity.astro": [
    { q: "How is e-way bill validity calculated in 2026?", a: "For standard vehicles, validity is 1 day for every 200 km. For Over Dimensional Cargo (ODC), it is 1 day for every 20 km travelled." },
    { q: "Can e-way bill validity be extended?", a: "Yes, the validity can be extended online on the e-way bill portal, but it must be done within 8 hours before or after the original expiry time." }
  ],
  "gst-interest-calculator.astro": [
    { q: "What is the interest rate for late payment of GST in 2026?", a: "The standard interest rate for late payment of GST is 18% per annum, calculated on the net cash tax liability from the day after the due date." },
    { q: "How is GST interest calculated on late filing?", a: "Interest is calculated daily using the formula: (Net Tax Liability × 18% × Number of Days Delayed) ÷ 365." }
  ],
  "gst-penalty-calculator.astro": [
    { q: "What is the penalty for not issuing a GST invoice?", a: "The penalty for not issuing an invoice or issuing a false invoice is 100% of the tax evaded or ₹10,000, whichever is higher." },
    { q: "Is there a penalty for wrong ITC claim?", a: "Yes. Claiming excessive or fraudulent Input Tax Credit (ITC) attracts a penalty of ₹10,000 or 100% of the tax amount involved, whichever is higher." }
  ],
  "itc-calculator.astro": [
    { q: "What are the rules for claiming ITC in 2026?", a: "In 2026, you can only claim ITC if the invoice appears in your GSTR-2B. Provisional ITC is no longer allowed." },
    { q: "Can I claim ITC on capital goods?", a: "Yes, you can claim ITC on capital goods used for business purposes, but you cannot claim both depreciation on the GST component and ITC simultaneously." }
  ],
  "rcm-calculator.astro": [
    { q: "What is the Reverse Charge Mechanism (RCM)?", a: "Under normal circumstances, the supplier pays GST. Under RCM, the liability to pay GST falls on the recipient of the goods or services." },
    { q: "Can I claim ITC on tax paid under RCM?", a: "Yes. You must first pay the RCM liability in cash, and then you can claim it back as Input Tax Credit in the same month's GSTR-3B, provided it's used for business." }
  ],
  "tcs-gst-calculator.astro": [
    { q: "What is the TCS rate under GST in 2026?", a: "E-commerce operators are required to collect TCS at the rate of 1% (0.5% CGST + 0.5% SGST, or 1% IGST) on the net value of taxable supplies made through their platform." },
    { q: "Who is liable to collect TCS under GST?", a: "Only specific e-commerce operators who facilitate the supply of goods or services (like Amazon, Flipkart, or Swiggy) are liable to collect TCS." }
  ],
  "tds-gst-calculator.astro": [
    { q: "What is the TDS rate under GST?", a: "The TDS rate under GST is 2% (1% CGST + 1% SGST, or 2% IGST) on payments made to suppliers for taxable goods or services." },
    { q: "When is TDS deducted under GST?", a: "TDS is deducted by specified government agencies, local authorities, and PSUs when the total value of supply under a single contract exceeds ₹2,50,000." }
  ]
};

for (const [filename, missingFaqs] of Object.entries(faqData)) {
  const filePath = path.join('src', 'pages', filename);
  if (!fs.existsSync(filePath)) {
    console.log(`File not found: ${filePath}`);
    continue;
  }
  
  let content = fs.readFileSync(filePath, 'utf8');

  // Inject into structuredData array
  // We need to find `mainEntity: [` or `mainEntity:[\n`
  const mainEntityRegex = /(mainEntity:\s*\[)/;
  if (mainEntityRegex.test(content)) {
    let schemaInjections = missingFaqs.map(faq => `\n      { '@type': 'Question', name: ${JSON.stringify(faq.q)}, acceptedAnswer: { '@type': 'Answer', text: ${JSON.stringify(faq.a)} } },`).join('');
    content = content.replace(mainEntityRegex, `$1${schemaInjections}`);
  }

  // Inject into HTML details array
  // We look for `{[ \n` or `{[ ` or `{\s*\[\s*` inside the FAQ Section
  const htmlArrayRegex = /(FAQ Section[\s\S]*?\{\s*\[)/;
  if (htmlArrayRegex.test(content)) {
    let htmlInjections = missingFaqs.map(faq => `\n          { q: ${JSON.stringify(faq.q)}, a: ${JSON.stringify(faq.a)} },`).join('');
    content = content.replace(htmlArrayRegex, `$1${htmlInjections}`);
  } else {
    // some use structuredData[1].mainEntity.map
    // If it uses structuredData mapping, we don't need to inject into the HTML array manually!
    // It will automatically render from structuredData. 
    // We just need to make sure the structuredData injection succeeded.
  }

  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Injected ${missingFaqs.length} FAQs into ${filename}`);
}
